services:
    postgres:
        image: postgres:16
        pull_policy: weekly
        tty: true
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:${POSTGRESQL_PORT}:5432"
        environment:
            POSTGRES_USER: ${POSTGRESQL_USER}
            POSTGRES_PASSWORD: ${POSTGRESQL_PWD_DECODED}
            POSTGRES_DB: ${POSTGRESQL_DB}
        networks:
            - postgres

    imgproxy:
        image: darthsim/imgproxy:v3
        pull_policy: weekly
        volumes:
            - ./uploads:/uploads:ro
        ports:
            - "127.0.0.1:${IMGPROXY_PORT}:8080"
        environment:
            IMGPROXY_KEY: ${IMGPROXY_KEY}
            IMGPROXY_SALT: ${IMGPROXY_SALT}
            IMGPROXY_MAX_SRC_RESOLUTION: 70
            IMGPROXY_LOCAL_FILESYSTEM_ROOT: "/uploads"
            IMGPROXY_USE_ABS: ${IMGPROXY_USE_ABS}
            IMGPROXY_ABS_NAME: ${AZURE_ACCOUNT_NAME}
            IMGPROXY_ABS_KEY: ${AZURE_ACCOUNT_KEY}
            IMGPROXY_USE_S3: ${IMGPROXY_USE_S3}
            IMGPROXY_S3_REGION: ${S3_REGION}
            IMGPROXY_S3_ENDPOINT: ${S3_ENDPOINT}
            AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}

    jaeger:
        image: jaegertracing/all-in-one:1
        pull_policy: weekly
        ports:
            - "127.0.0.1:${JAEGER_UI_PORT}:16686"
            - "127.0.0.1:${JAEGER_OLTP_PORT}:4318" #OLTP over HTTP
        environment:
            COLLECTOR_OTLP_ENABLED: "true"
            COLLECTOR_OTLP_HTTP_HOST_PORT: 0.0.0.0:4318

    mailpit:
        image: axllent/mailpit
        pull_policy: weekly
        ports:
            - "127.0.0.1:1025:1025" # SMTP server
            - "127.0.0.1:8025:8025" # Web UI

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
        driver: local
