name: CI

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - closed
        branches:
            - main
            - next

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor }}"

            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}

            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com

            - name: Use Node.js 14.x
              uses: actions/setup-node@v3
              with:
                  node-version: 14
                  registry-url: "https://registry.npmjs.org"
                  cache: "yarn" # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

            - name: Install NPM 7.x
              run: npm install -g npm@7.19

            - run: yarn install

            - name: Copy schema files
              run: |
                  cp packages/api/cms-api/block-meta.json packages/admin/blocks-admin/block-meta.json
                  cp packages/api/cms-api/schema.gql packages/admin/cms-admin/schema.gql
                  cp packages/api/cms-api/block-meta.json packages/admin/cms-admin/block-meta.json
                  cp packages/api/cms-api/block-meta.json packages/site/cms-site/block-meta.json
                  cp demo/api/block-meta.json demo/admin/block-meta.json
                  cp demo/api/block-meta.json demo/site/block-meta.json
                  cp demo/api/schema.gql demo/admin/schema.gql
                  cp demo/api/schema.gql demo/site/schema.gql

            - name: Build
              run: yarn build:lib

            - name: Lint
              run: |
                  yarn exec prettier --check "./*.{js,json,md,yml}"
                  yarn lint:lib
                  # check for duplicate ids of formatted messages
                  yarn intl:extract

            - name: Test
              run: yarn test:lib

            - name: Test Report
              uses: dorny/test-reporter@v1
              if: success() || failure()
              with:
                  name: Tests
                  path: packages/**/junit.xml
                  reporter: jest-junit

            - name: "Library: Clone translations"
              if: ${{ github.ref_name == 'next' }} # TODO: change me to main
              uses: actions/checkout@v3
              with:
                  repository: vivid-planet/comet-lang
                  token: ${{ secrets.GH_TOKEN }}
                  path: "comet-lang"

            - name: "Library: Extract i18n strings"
              if: ${{ github.ref_name == 'next' }} # TODO: change me to main
              run: |
                  yarn intl:extract
                  cp -r lang/* comet-lang/

            - name: "Library: Update translateable strings"
              if: ${{ github.ref_name == 'next' }} # TODO: change me to main
              uses: EndBug/add-and-commit@v9
              with:
                  cwd: "./comet-lang"

            - name: "Demo: Clone translations"
              if: ${{ github.ref_name == 'next' }} # TODO: change me to main
              uses: actions/checkout@v3
              with:
                  repository: vivid-planet/comet-demo-lang
                  token: ${{ secrets.GH_TOKEN }}
                  path: "demo/admin/comet-demo-lang"

            - name: "Demo: Extract i18n strings"
              if: ${{ github.ref_name == 'next' }} # TODO: change me to main
              run: |
                  cd demo/admin
                  yarn intl:extract
                  cp -r lang-extracted/* comet-demo-lang/

            - name: "Demo: Update translateable strings"
              if: ${{ github.ref_name == 'next' }} # TODO: change me to main
              uses: EndBug/add-and-commit@v9
              with:
                  cwd: "./demo/admin/comet-demo-lang"

            - name: Publish premajor canary release
              if: |
                  !contains( github.event.pull_request.labels.*.name, 'skip-release') &&
                  github.base_ref == 'next' &&
                  github.event.pull_request.merged == true
              run: yarn publish:release premajor --no-push --no-git-tag-version --canary --preid=canary.${{ github.run_number }} --dist-tag=canary --yes
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish stable minor release
              if: |
                  !contains( github.event.pull_request.labels.*.name, 'skip-release') &&
                  github.base_ref == 'main' &&
                  github.event.pull_request.merged == true
              run: yarn publish:release minor --yes
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
