name: CI

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"
        branches:
            - main
            - next
    pull_request:
        branches:
            - main
            - next

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor }}"

            - name: Dump GitHub context
              run: echo '${{ toJSON(github) }}'

            - uses: actions/checkout@v3

            - name: Use Node.js 14.x
              uses: actions/setup-node@v3
              with:
                  node-version: 14
                  registry-url: "https://registry.npmjs.org"
                  cache: "yarn" # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

            - run: yarn install

            - name: Build
              run: yarn build

            - name: Lint
              run: |
                  yarn exec prettier -c .
                  yarn lint

            - name: Extract i18n strings
              if: ${{ github.ref_name == 'main' }}
              run: |
                  yarn intl:extract
                  git clone https://github.com/vivid-planet/comet-admin-lang.git
                  cp -r lang/* comet-admin-lang/
                  cd comet-admin-lang
                  git config user.email "vivid-planet-bot@vivid-planet.com"
                  git add .
                  if [[ `git status --porcelain` ]]; then git commit -m "add translatable strings for ${{ github.sha }}" && git remote rm origin && git remote add origin https://vivid-planet-bot:${{ secrets.GH_TOKEN }}@github.com/vivid-planet/comet-admin-lang.git && git push --set-upstream origin master; fi

            - name: Publish Canary release
              if: ${{ github.ref_name == 'main' || github.ref_name == 'next' }}
              run: yarn publish:release --canary --preid=canary --dist-tag=canary --yes
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish stable release
              if: ${{ github.ref_type == 'tag' }}
              run: yarn publish:release ${{ github.ref_name }} --yes
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
