name: CI

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - closed
        branches:
            - main
            - next
    push:
        tags:
            - "v*"

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor }}"

            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}

            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com

            - name: "Library: Clone translations"
              uses: actions/checkout@v3
              with:
                  repository: vivid-planet/comet-lang
                  token: ${{ secrets.GH_TOKEN }}
                  path: "demo/admin/lang/comet-lang"

            - name: "Demo: Clone translations"
              uses: actions/checkout@v3
              with:
                  repository: vivid-planet/comet-demo-lang
                  token: ${{ secrets.GH_TOKEN }}
                  path: "demo/admin/lang/comet-demo-lang"

            - name: Use Node.js 14.x
              uses: actions/setup-node@v3
              with:
                  node-version: 14
                  registry-url: "https://registry.npmjs.org"
                  cache: "yarn" # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

            - name: Install NPM 7.x
              run: npm install -g npm@7.19

            - run: yarn install

            - name: Copy schema files
              run: yarn copy-schema-files

            - name: Build
              run: yarn build:lib

            - name: Lint
              run: |
                  yarn exec prettier --check "./*.{js,json,md,yml}"
                  yarn lint
                  # check for duplicate ids of formatted messages
                  yarn intl:extract

            - name: Test
              run: yarn test:lib

            - name: Test Report
              uses: dorny/test-reporter@v1
              if: github.actor != 'dependabot[bot]' && (success() || failure())
              with:
                  name: Tests
                  path: packages/**/junit.xml
                  reporter: jest-junit

            - name: "Library: Extract i18n strings"
              if: ${{ github.ref_name == 'main' }}
              run: |
                  yarn intl:extract
                  cp -r lang/* demo/admin/lang/comet-lang/

            - name: "Library: Update translateable strings"
              if: ${{ github.ref_name == 'main' }}
              uses: EndBug/add-and-commit@v9
              with:
                  cwd: "./demo/admin/lang/comet-lang"

            - name: "Demo: Extract i18n strings"
              if: ${{ github.ref_name == 'main' }}
              run: |
                  cd demo/admin
                  yarn intl:extract
                  cp -r lang-extracted/* lang/comet-demo-lang

            - name: "Demo: Update translateable strings"
              if: ${{ github.ref_name == 'main' }}
              uses: EndBug/add-and-commit@v9
              with:
                  cwd: "./demo/admin/lang/comet-demo-lang"

            - name: Publish premajor canary release
              if: |
                  !contains( github.event.pull_request.labels.*.name, 'skip-release') &&
                  github.base_ref == 'next' &&
                  github.event.pull_request.merged == true
              run: yarn publish:release premajor --no-push --no-git-tag-version --canary --preid=canary.${{ github.run_number }} --dist-tag=canary --yes
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish preminor canary release
              if: |
                  !contains( github.event.pull_request.labels.*.name, 'skip-release') &&
                  github.ref_name != 'next' &&
                  github.base_ref == 'main' &&
                  github.event.pull_request.merged == true
              run: yarn publish:release preminor --no-push --no-git-tag-version --canary --preid=alpha.${{ github.run_number }} --dist-tag=alpha --yes
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: "Publish stable version"
              if: startsWith(github.event.ref, 'refs/tags/v')
              run: yarn publish:release from-git --yes
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
